dist: trusty
language: node_js
node_js:
  - "stable"

branches:
  only:
  - master
  - development

script: |
  .travis.d/build.sh

addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
